export enum ErrorCodes {
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
    DATABASE_ERROR = 'DATABASE_ERROR',
    MAINTENANCE = 'MAINTENANCE',
    NOT_IMPLEMENTED = 'NOT_IMPLEMENTED',
    VALIDATION = 'VALIDATION',
    ALREADY_EXISTS = 'ALREADY_EXISTS',
    NOT_FOUND = 'NOT_FOUND',
    BAD_REQUEST = 'BAD_REQUEST',
}
